name: "Home Assistant socat Add-On"
description: "Run socat as Home Assistant Add-On"
version: "0.1.0"
slug: "socat"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - /dev/ttyUSB0
  - /dev/ttyV0
ports:
  12345/tcp: 12345
options:
  cli: null
schema:
  cli: str
